version: '3'

tasks:
  default:
    desc: Show all available tasks with descriptions and usage
    cmds:
      - echo 'Available Tasks:'
      - task --list-all
        

  migrate:
    desc: Run database migrations using psql
    cmds:
      - psql -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres} -h ${DB_HOST:-localhost} -p ${DB_PORT:-5433} -f db/migrations/001_init.sql
    env:
      PGPASSWORD: "${DB_PASSWORD:-}"

  build:
    desc: Build the Go application
    cmds:
      - go build -o bin/transactions main.go

  run:
    desc: Run the Go application
    cmds:
      - go run main.go

  test:
    desc: Run all Go tests
    cmds:
      - go test ./... -v

  reset:
    desc: Drop and recreate the database, then run migrations
    cmds:
      - psql -U ${DB_USER:-postgres} -h ${DB_HOST:-localhost} -p ${DB_PORT:-5433} -c "DROP DATABASE IF EXISTS ${DB_NAME:-postgres};"
      - psql -U ${DB_USER:-postgres} -h ${DB_HOST:-localhost} -p ${DB_PORT:-5433} -c "CREATE DATABASE ${DB_NAME:-postgres};"
      - task migrate
    env:
      PGPASSWORD: "${DB_PASSWORD:-}" 