version: '3'

tasks:
  default:
    desc: Show all available tasks with descriptions and usage
    cmds:
      - echo 'Available Tasks:'
      - task --list-all
        
  build:
    desc: Build the Go application
    cmds:
      - go build -o bin/transactions main.go

  run:
    desc: Run the Go application
    cmds:
      - go run main.go

  test:
    desc: Run all Go tests
    cmds:
      - go test ./... -v
